### ISSUE TITLE
Figure illustrating relationship between YAML, data model and parser

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-paper#15]
I think it would be helpful if our Figure 1 could show a simple (but featureful) Demes model in YAML along with a depiction of the corresponding fully qualified model, with a "Parser" in the middle (i.e., showing that the job of the parser is to turn the non-redundant YAML (or JSON I guess) description into a fully qualified object model that simulators can use as input. I think this would really help people understand the architecture.

Maybe a simple three population "tree", (A, B) -> C, with a defaults section would be good to illustrate things? It's hard to know what'll work until we try things out. I guess ideally we'd illustrate things with a model from the literature, but the fully qualified representation might be too verbose then.

**Comment by grahamgower** [comment]
Good idea. We might struggle to display a small enough version of the fully-qualifed output though.
```yaml
time_units: generations
defaults:
  epoch: {start_size: 1000}
demes:
  - name: A
    epochs:
      - end_time: 100
  - name: B
    ancestors: [A]
  - name: C
    ancestors: [A]
migrations:
  - {demes: [B, C], rate: 1e-4}
```

Resolved output from demes-c.
```yaml
---
time_units: generations
demes:
- name: A
  start_time: .inf
  epochs:
  - end_time: 100
    start_size: 1000
    end_size: 1000
    size_function: constant
    selfing_rate: 0
    cloning_rate: 0
- name: B
  start_time: 100
  ancestors: [A]
  proportions: [1]
  epochs:
  - end_time: 0
    start_size: 1000
    end_size: 1000
    size_function: constant
    selfing_rate: 0
    cloning_rate: 0
- name: C
  start_time: 100
  ancestors: [A]
  proportions: [1]
  epochs:
  - end_time: 0
    start_size: 1000
    end_size: 1000
    size_function: constant
    selfing_rate: 0
    cloning_rate: 0
migrations:
- {source: B, dest: C, start_time: 100, end_time: 0, rate: 0.0001}
- {source: C, dest: B, start_time: 100, end_time: 0, rate: 0.0001}
...
```

Or the slightly more compact form from demes-python:
```yaml
time_units: generations
demes:
- name: A
  start_time: .inf
  epochs:
  - {end_time: 100, start_size: 1000, end_size: 1000, size_function: constant, selfing_rate: 0,
    cloning_rate: 0}
- name: B
  start_time: 100
  ancestors: [A]
  proportions: [1.0]
  epochs:
  - {end_time: 0, start_size: 1000, end_size: 1000, size_function: constant, selfing_rate: 0,
    cloning_rate: 0}
- name: C
  start_time: 100
  ancestors: [A]
  proportions: [1.0]
  epochs:
  - {end_time: 0, start_size: 1000, end_size: 1000, size_function: constant, selfing_rate: 0,
    cloning_rate: 0}
migrations:
- {source: B, dest: C, start_time: 100, end_time: 0, rate: 0.0001}
- {source: C, dest: B, start_time: 100, end_time: 0, rate: 0.0001}
```
